-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('hello_pb')


local HELLO = protobuf.Descriptor();
local HELLO_EHOBBY = protobuf.EnumDescriptor();
local HELLO_EHOBBY_FOOTBALL_ENUM = protobuf.EnumValueDescriptor();
local HELLO_EHOBBY_BASKETBALL_ENUM = protobuf.EnumValueDescriptor();
local HELLO_EHOBBY_SWIMMING_ENUM = protobuf.EnumValueDescriptor();
local HELLO_EHOBBY_PINGPANG_ENUM = protobuf.EnumValueDescriptor();
local HELLO_AGE_FIELD = protobuf.FieldDescriptor();
local HELLO_NAME_FIELD = protobuf.FieldDescriptor();
local HELLO_IS_MALE_FIELD = protobuf.FieldDescriptor();
local HELLO_HOBBIES_FIELD = protobuf.FieldDescriptor();

HELLO_EHOBBY_FOOTBALL_ENUM.name = "football"
HELLO_EHOBBY_FOOTBALL_ENUM.index = 0
HELLO_EHOBBY_FOOTBALL_ENUM.number = 0
HELLO_EHOBBY_BASKETBALL_ENUM.name = "basketball"
HELLO_EHOBBY_BASKETBALL_ENUM.index = 1
HELLO_EHOBBY_BASKETBALL_ENUM.number = 1
HELLO_EHOBBY_SWIMMING_ENUM.name = "swimming"
HELLO_EHOBBY_SWIMMING_ENUM.index = 2
HELLO_EHOBBY_SWIMMING_ENUM.number = 2
HELLO_EHOBBY_PINGPANG_ENUM.name = "pingpang"
HELLO_EHOBBY_PINGPANG_ENUM.index = 3
HELLO_EHOBBY_PINGPANG_ENUM.number = 3
HELLO_EHOBBY.name = "EHobby"
HELLO_EHOBBY.full_name = ".hello.EHobby"
HELLO_EHOBBY.values = {HELLO_EHOBBY_FOOTBALL_ENUM,HELLO_EHOBBY_BASKETBALL_ENUM,HELLO_EHOBBY_SWIMMING_ENUM,HELLO_EHOBBY_PINGPANG_ENUM}
HELLO_AGE_FIELD.name = "age"
HELLO_AGE_FIELD.full_name = ".hello.age"
HELLO_AGE_FIELD.number = 1
HELLO_AGE_FIELD.index = 0
HELLO_AGE_FIELD.label = 1
HELLO_AGE_FIELD.has_default_value = true
HELLO_AGE_FIELD.default_value = 18
HELLO_AGE_FIELD.type = 5
HELLO_AGE_FIELD.cpp_type = 1

HELLO_NAME_FIELD.name = "name"
HELLO_NAME_FIELD.full_name = ".hello.name"
HELLO_NAME_FIELD.number = 2
HELLO_NAME_FIELD.index = 1
HELLO_NAME_FIELD.label = 2
HELLO_NAME_FIELD.has_default_value = false
HELLO_NAME_FIELD.default_value = ""
HELLO_NAME_FIELD.type = 9
HELLO_NAME_FIELD.cpp_type = 9

HELLO_IS_MALE_FIELD.name = "is_male"
HELLO_IS_MALE_FIELD.full_name = ".hello.is_male"
HELLO_IS_MALE_FIELD.number = 3
HELLO_IS_MALE_FIELD.index = 2
HELLO_IS_MALE_FIELD.label = 1
HELLO_IS_MALE_FIELD.has_default_value = true
HELLO_IS_MALE_FIELD.default_value = true
HELLO_IS_MALE_FIELD.type = 8
HELLO_IS_MALE_FIELD.cpp_type = 7

HELLO_HOBBIES_FIELD.name = "hobbies"
HELLO_HOBBIES_FIELD.full_name = ".hello.hobbies"
HELLO_HOBBIES_FIELD.number = 4
HELLO_HOBBIES_FIELD.index = 3
HELLO_HOBBIES_FIELD.label = 3
HELLO_HOBBIES_FIELD.has_default_value = false
HELLO_HOBBIES_FIELD.default_value = {}
HELLO_HOBBIES_FIELD.enum_type = HELLO_EHOBBY
HELLO_HOBBIES_FIELD.type = 14
HELLO_HOBBIES_FIELD.cpp_type = 8

HELLO.name = "hello"
HELLO.full_name = ".hello"
HELLO.nested_types = {}
HELLO.enum_types = {HELLO_EHOBBY}
HELLO.fields = {HELLO_AGE_FIELD, HELLO_NAME_FIELD, HELLO_IS_MALE_FIELD, HELLO_HOBBIES_FIELD}
HELLO.is_extendable = false
HELLO.extensions = {}

hello = protobuf.Message(HELLO)

